# Site settings
title: École Montessori de Melun - Vaux-le-Pénil
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.ecole-montessori-melun.com"

# Permalinks
permalink: :year/:month/:title.html

# Just for local server
port: 4321

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  header_offset: 1

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile*
  - README.md
  - LICENSE.md
include:
  - favicon.jpg

